### ISSUE TITLE
Ability to check if Trezor connection is available

### ISSUE THREAD

**Issue by axic** [trezor/trezor.js#24]
Currently, if connection cannot be established (either due to device not connected or support not available) the `error` callback on `DeviceList` will return with:
`Error: Loading timed out`

That is because the load order as of 4.1.0 is chrome, bridge, plugin and the plugin has the error message.

I am displaying messages (and errors) on `DeviceList` events via Toastr, which is working nicely. However this one error is a bit confusing as in many cases I shouldn't display it.

It is possible to check for that given message and not display it, but there must be a better solution.

I think another event, such as `notsupported` would be better, while keeping other errors in the `error` event.

**Comment by axic** [comment]
What do you think @runn1ng?

**Comment by runn1ng** [comment]
Yep, you are right. We do a slight refactoring right now, I think there will be better error then.

Anyway, right now, you can check if `deviceList.transport` is null or not, and if it's null, provide the user some info about installing extension/bridge.

(Plugin is discontinued, it is slowly stopping to work in browsers.)

**Comment by axic** [comment]
I assume `deviceList.transport` is set asynchronously so my best bet is to check if it s not set in the `error` callback:

```js
list.on('error', function () {
  if (!list.transport)
    // software not available
  else
    // normal error
})
```

**Comment by runn1ng** [comment]
Yep, that's what I meant

Anyway I will let this issue open and will close it after refactor

**Comment by karel-3d** [comment]
Ooph, this is probably done right now? Please reopen if it is still valid
