### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by canguruhh** [trezor/trezor.js#49]
Readme says:
Example of usage is on example-browser/, example-node/ and example-electron-webpack/ on github.

However in the example folder there is only one example.js

**Comment by wbobeirne** [comment]
I also noticed this, however the code that you get from npm does have it in `node_modules/trezor.js` or `node_modules/trezor.js-node`. I also can't find where `trezor.js-node`'s readme is in this repo. I'm assuming their publish process, or up to date source code isn't actually in GitHub.

**Comment by karel-3d** [comment]
sorry for the mixups. trezor.js-node is now removed. The example should work in both
