### ISSUE TITLE
Possible light-weight js library

### ISSUE THREAD

**Issue by andrewheadricke** [trezor/trezor.js#56]
I would like my web app to be able to connect to `trezord-go` so that I can enumerate my accounts and potentially sign transactions.  I compiled `trezor.js` using browserify and it resulted in a 2Mb bundle (1.2Mb compressed).  That seems quite high.  Is it possible to get a simplified version that just does the basics?  Or would it not save much?

**Comment by karel-3d** [comment]
Sorry. You are free to fork, if it is for node, and please make a PR if you find something.

If it is for website, trezor.js is not a good idea anyway, use Connect

**Comment by andrewheadricke** [comment]
Do you know if its possible to use Trezor Connect offline or without the dependency of connecting to trezor.com to use my device?
