### ISSUE TITLE
bchaddrjs missing from package.json

### ISSUE THREAD

**Issue by wbobeirne** [trezor/trezor.js#57]
`bchaddrjs` is imported here: https://github.com/trezor/trezor.js/blob/922c163d445700774d5601446e300b3e2fd01a40/src/utils/signbjstx.js#L4 but is not located in package.json dependencies. This causes the following error:

```
ERROR in ./node_modules/trezor.js/lib/utils/signbjstx.js
Module not found: Error: Can't resolve 'bchaddrjs' in 
  '/<redacted>/node_modules/trezor.js/lib/utils'
```

It can be fixed by installing the dependency yourself, but it should be included in trezor.js' package.json

**Comment by karel-3d** [comment]
fixed, thanks for noticing
