### ISSUE TITLE
Refactoring session.js

### ISSUE THREAD

**Issue by alepop** [trezor/trezor.js#64]
While added new coins functionality to Session class (eth, lisk, nem... ) it becomes bigger and bigger and has a lot of same methods with different names. To avoid this type of mess, I suggest moving altcoins logic to separate classes and extend `Session` with it on initialization process. We can extend session object with all altcoins methods, this will allow using trezor.js API like how it is now, or move each altcoin logic to the namespace. 
How it looks now:
`session.liskGetAddress`
How it can looks: 
1) `session.lisk.getAddress`
2) `session.altcoins.liskGetAddress`

**Comment by prusnak** [comment]
The thing is we won't be needed any altcoin functions in the trezor.js soon as every parameter would be sent using a JSON structure, so we won't need a specific function for every call.
