### ISSUE TITLE
Support for arbitrary (non-standard) tx inputs

### ISSUE THREAD

**Issue by bodymindarts** [trezor/trezor.js#67]
The TransactionInput type only supports a specific set of input types:
```
script_type?: 'SPENDADDRESS' | 'SPENDMULTISIG' | 'EXTERNAL' | 'SPENDWITNESS' | 'SPENDP2SHWITNESS';
```

I need to sign inputs that contain additional logic (eg. op_CHECKSEQUENCEVERIFY). Would it be possible to add support for a script_type `NON_STANDARD` that require the fields:
```
redeem_script?: string
witness_script?: string
```
In order to be able to sign them with the trezor?

**Comment by bodymindarts** [comment]
Ah I think this is taken care of via signBjsTx

**Comment by karel-3d** [comment]
Trezor cannot sign these type of transactions. See

https://github.com/trezor/trezor-common/blob/master/protob/messages-bitcoin.proto#L12

This is an issue for repos trezor-mcu (trezor 1) and/or trezor-core (trezor t)

**Comment by karel-3d** [comment]
Trezor has intentionally a limited set of scripts it makes, so it can display the logic on the display.

Any additional logic - like op_CHECKSEQUENCEVERIFY - has to be done in the firmware itself, so it can display that to the user correctly.

You cannot sign arbitrary scripts on trezor.

**Comment by prusnak** [comment]
That said, Trezor is open-source so you can modify the firmware and add the functionality you need, such as signing custom scripts.
