### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by yahyameo** [trezor/trezor.js#81]
```
{v: 41, r: "6bf92ebeda9154e0b5a712958688567c289f75e15461d3db9d3eea57c3249881", s: "0068d2b442fed991aeaa09c92204744fa2b694cfd7d5262652f24f0585fe8d57"}r: "6bf92ebeda9154e0b5a712958688567c289f75e15461d3db9d3eea57c3249881"s: "0068d2b442fed991aeaa09c92204744fa2b694cfd7d5262652f24f0585fe8d57"v: 41__proto__: Object
transactionService.js:441 0xf86a80850737be7600825208948af6b8fa24314d2eae3bf804323a02a3bffa7af88711c37937e080008029a06bf92ebeda9154e0b5a712958688567c289f75e15461d3db9d3eea57c32498819f68d2b442fed991aeaa09c92204744fa2b694cfd7d5262652f24f0585fe8d57
transactionService.js:450 Error: insufficient funds for gas * price + value
    at Object.InvalidResponse (web3.min.js:1)
    at web3.min.js:1
    at XMLHttpRequest.r.onreadystatechange (web3.min.js:1)
```

**Comment by prusnak** [comment]
1) don't use trezor.js directly, but rather use Trezor Connect: https://github.com/trezor/connect
2) you need to show us the code which produces this error

**Comment by prusnak** [comment]
Why don't you use Connect instead like I suggested?

**Comment by yahyameo** [comment]
We are using trezor.js as it is stable version, and if we use Connect then might we need to make a lot of changes. Please assist us if we can go with trezor.js after removing above mentioned error. We even facing issue when signing bitcoin transactions.

**Comment by yahyameo** [comment]
@prusnak we get values for v,r,s after signing tx with device but getting this issue when transaction is broadcasted over network

**Comment by prusnak** [comment]
Please use Connect like you are supposed to
