### ISSUE TITLE
 fsm.c:218:Failed to derive private key

### ISSUE THREAD

**Issue by yahyameo** [trezor/trezor.js#85]
I get this error when i try to create NEM address
code:
```
device.waitForSessionAndRun(function (session) {
        //bip44id for NEM Coin
        var network=104;
       return session.nemGetAddress([
        (44 | hardeningConstant) >>> 0,
        (43| hardeningConstant) >>> 0,
        (0 | hardeningConstant) >>> 0,
        0,
        0
        ],network,false);
});
```

**Comment by prusnak** [comment]
You can't use public derivations (without hardeningConstant) for NEM.

The correct path is: 44'/43'/a' where a is the account number. See https://github.com/trezor/trezor-core/tree/master/docs/coins

**Comment by yahyameo** [comment]
Thanks it's working now, i did the same way you proposed.
