### ISSUE TITLE
Invalid coin name

### ISSUE THREAD

**Issue by yahyameo** [trezor/trezor.js#86]
I get this error when trying to create addresses for the following coin using this method.
//for like BCH:145
```
var hardeningConstant = 0x80000000;
        return device.waitForSessionAndRun(function (session) { 
            return session.getAddress([
                (44 | hardeningConstant) >>> 0,
                (145| hardeningConstant) >>> 0,
                (0 | hardeningConstant) >>> 0,
                0,
                0
            ], "Bitcoin Cash", false)
        })
```
Bitcoin Cash
Bitcoin Gold 
MonaCoin
ZCoin
FujiCoin
Pesetacoin

Note:Does trezor support above coins?

**Comment by prusnak** [comment]
Use `coin_name` field from the files here: https://github.com/trezor/trezor-common/tree/master/defs/bitcoin, that is 

Bcash
Bgold
Monacoin
Zcoin
Fujicoin
not sure what is wrong with the last one

**Comment by yahyameo** [comment]
Thanks for your time and consideration. All coins are done except `Pesetacoin` . I am using same method but no success
