### ISSUE TITLE
Digest method not supported

### ISSUE THREAD

**Issue by KevinBaiSg** [trezor/trezor.js#94]
why call the session.getAddress, it return error: Digest method not supported?

**Comment by prusnak** [comment]
Don't use trezor.js directly. Use https://github.com/trezor/connect instead

**Comment by KevinBaiSg** [comment]
@prusnak I want to develop an application base on Electron, but connect don't support electron

**Comment by prusnak** [comment]
It will soon.

**Comment by KevinBaiSg** [comment]
thanks @prusnak, because of window.open() failed in electron project. Can I remove the iframe from connect, do you have some suggestion?
