### ISSUE TITLE
Recommended way to interface directly with bridge if this library is no longer being supported?

### ISSUE THREAD

**Issue by floating** [trezor/trezor.js#96]
This library is relied upon by https://frame.sh, which runs locally on the user's machine. We've been using trezor.js to talk to Trezor Bridge and support all Trezor devices after the node-hid integration also became unsupported. If this library is no longer being maintained, what is the recommended way to interface directly with the bridge? We need to be able to interface to multiple devices at once and cannot support popup UI flows. Thank you for any info!

**Comment by prusnak** [comment]
The only supported way is to use Trezor Connect https://github.com/trezor/connect

In case you are missing any functionality in Connect, please open the issue there.
